### ISSUE TITLE
Enhancement Request: Incorporate Node Environment and Implement CI/CD in the Project

### ISSUE THREAD

**Issue by Bugz-gg** [RomainPierre7/airport_transport_service#1]
Currently, the project lacks a Node environment, which is essential for Node.js-based applications. To enhance the project structure, it is recommended to include both package.json and package-lock.json files to manage dependencies effectively.

Furthermore, incorporating Continuous Integration/Continuous Deployment (CI/CD) is crucial for streamlining the development process. GitHub Actions provides a straightforward solution for implementing CI/CD, offering automation opportunities that can significantly simplify team collaboration and improve overall programming efficiency.

Consider implementing these enhancements promptly to the overall quality and maintainability of your project. 
:+1:

**Comment by RomainPierre7** [comment]
Dear Bugz,

Given the initial phase of the project, it's quite normal that the CI/CD is not yet complete. Our best dev ops are on the job. If you are interested, please stay tuned, as we regularly offer new job opportunities in our company.

Yours sincerely

Romain - C.T.O.
